language: r
warnings_are_errors: true

cache: packages

sudo: required

r_github_packages:
  - jimhester/covr
  - SteffenMoritz/ridge

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgsl0-dev

after_success:
  - Rscript -e 'library(covr);codecov()'